# Generated by Django 4.2.7 on 2023-12-12 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FCINCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FCIN', models.CharField(max_length=40, unique=True)),
                ('company_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('activity', models.CharField(max_length=50)),
                ('activity_description', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('office_type', models.TextField(null=True)),
                ('address', models.TextField(null=True)),
                ('state', models.CharField(max_length=50)),
                ('month', models.CharField(max_length=20, null=True)),
                ('year', models.IntegerField(null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('file_name', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndianCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CIN', models.CharField(max_length=60, unique=True)),
                ('company_name', models.CharField(max_length=255)),
                ('date_of_registration', models.DateField()),
                ('month_name', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=50)),
                ('roc', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255, null=True)),
                ('Class', models.CharField(max_length=50, null=True)),
                ('company_type', models.CharField(max_length=50, null=True)),
                ('authorized_capital', models.DecimalField(decimal_places=2, max_digits=50, null=True)),
                ('paid_up_capital', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('activity', models.CharField(max_length=255, null=True)),
                ('activity_description', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('registered_office_address', models.TextField()),
                ('month', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('file_name', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LLPCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LLPIN', models.CharField(max_length=80, unique=True)),
                ('llp_name', models.CharField(max_length=255)),
                ('founded', models.DateField()),
                ('roc_location', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('industrial_activity', models.CharField(max_length=50)),
                ('activity_description', models.TextField()),
                ('description', models.TextField()),
                ('obligation_of_contribution', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('number_of_partners', models.IntegerField(null=True)),
                ('number_of_designated_partners', models.IntegerField(null=True)),
                ('state', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('address', models.TextField(null=True)),
                ('month', models.CharField(max_length=20, null=True)),
                ('year', models.IntegerField(null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('file_name', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatusCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fetched_count', models.IntegerField()),
                ('total_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expiration_time', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
