# Generated by Django 4.2.7 on 2023-12-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0003_bulkfilemodels'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkfilemodels',
            name='month',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='bulkfilemodels',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
